# image_dir_path: Y:\GOA-AIGC\98-goaTrainingData\ArchOctopus\archcollege
# stroed_embeddings_save_path: Y:\GOA-AIGC\98-goaTrainingData\ArchOctopus\archcollege-embedding
# 
# image_dir_path: Y:\GOA-AIGC\98-goaTrainingData\ArchOctopus_thumbnail_200px
# stroed_embeddings_save_path:  Y:\GOA-AIGC\98-goaTrainingData\ArchOctopus_thumbnail_200px
image_dir_path: D:\Ai-clip-seacher\AiArchLib1k
stroed_embeddings_save_path:  D:\Ai-clip-seacher\AiArchLib1k
traverse: true # true为迭代文件夹中的嵌套子文件夹
include_faces: false

reindex: true # false不判断图片库是否有更新，true判断保存的语义数据库与当前图片库是否一致，不一致则重新建立索引
n: 50

port:
host:
debug:
threaded:
